<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microcks.Testcontainers" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Checkout.Api/Checkout.Api.csproj" />
    <ProjectReference Include="../../src/Checkout.Application/Checkout.Application.csproj" />
    <ProjectReference Include="../../src/Checkout.Domain/Checkout.Domain.csproj" />
    <ProjectReference Include="../../src/Checkout.Infrastructure/Checkout.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
